### PR TITLE
chore: refactor to common zarf config and values files

### LINKED ISSUE #40: Update repo to utilize workflows, actions and tasks from the uds-common repo
### Describe what should be investigated or refactored
We created a repo to enable reuse of common uds tasks, gh actions and gh workflows. This repo should be updated to utilize the common ones where possible. 

### Links to any relevant code
https://github.com/defenseunicorns/uds-common

### Additional context
Any questions just ask.

### LINKED ISSUE #43: Update sonarqube repo to utilize zarf composability to keep the configuration DRY
### Describe what should be investigated or refactored
A standard we have developed for uds packages is to have common zarf components defines in a `common/zarf.yaml` and then have the flavor specific components import that common component. This keeps the configuration DRY and is easier to update. 

### Links to any relevant code
As an example look at the gitlab package:
[Common](https://github.com/defenseunicorns/uds-package-gitlab/blob/4ef3dd269a65cae83a29ca51654c0c6c1f9f0030/common/zarf.yaml#L8) 
[Importing common into flavored components](https://github.com/defenseunicorns/uds-package-gitlab/blob/4ef3dd269a65cae83a29ca51654c0c6c1f9f0030/zarf.yaml#L38)

This change also entails breaking values out into three sets, upstream-values.yaml (only includes image bits for upstream flavor), registry1-values.yaml (only includes image bits for registry1 flavor), and values (or common values) which contains the rest of the base values configuration. The flavor specific ones are imported in the root level flavor components and the common values is imported in the component in `common/zarf.yaml` 

### Additional context
If you have questions ask :)

### PR DESCRIPTION
**Pull request by ericwyles**
## Description
Refactor zarf.yaml to move shared values to a common/zarf.yaml and create flavor specific values files at values/registry1-values.yaml and values/upstream-values.yaml

In the process of refactoring this I also updated some of the github workflows to reference uds-common shared workflows.

In addition I attempted to use upstream chart for both flavors but it doesn't work, left a note in the README.md explaining why and referenced it from the chart reference in common/zarf.yaml (tracked in #48 )

## Related Issue

Fixes #43 
Fixes #40 
Relates to #48 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-sonarqube/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by ericwyles** [comment]
@zachariahmiller if you get a minute, could use some eyes on this one. Feels like I might be missing something here. The only part I was able to refactor out to common was the 'uds-sonarqube-config' chart. The 'sonarqube' chart has very little in common between the two flavors. Am I missing something more elegant here?

**Comment by zachariahmiller** [comment]
@ericwyles it actually looks like the only additional thing you could move to common is namespace. I hadnt realized when i created the issue two different charts were being used. We probably need to discuss which one we will use as we shouldnt be using two different ones. Apologies for the confusion

**Comment by ericwyles** [comment]
Will finish testing this after registry1 is up again.

**Comment by zachariahmiller** [comment]
@ericwyles updated the required checks to match the new convention

**Review by zachariahmiller — COMMENTED** [review]
I think this looks good. Just FYI if you are pulling in the latest setup action (0.2.2?) the publish will break as is currently `--no-progress` was accidentally dropped from `uds run` so you'll need to check the publish task https://github.com/defenseunicorns/uds-package-sonarqube/blob/f1679f7c7dae4c6bc301c020f6c43aec3e5cefbc/tasks/publish.yaml#L21

**Comment by ericwyles** [comment]
> I think this looks good. Just FYI if you are pulling in the latest setup action (0.2.2?) the publish will break as is currently `--no-progress` was accidentally dropped from `uds run` so you'll need to check the publish task
> 
> https://github.com/defenseunicorns/uds-package-sonarqube/blob/f1679f7c7dae4c6bc301c020f6c43aec3e5cefbc/tasks/publish.yaml#L21

Went ahead and removed --no-progress to save us a headache in the future.

**Review by zachariahmiller — APPROVED** [review]
🚢 🇮🇹  Appreciate you being a good sport basically implementing this twice to get it working!

**Pull request merged**
